name: portfolio_project
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  community_material_icon: ^5.9.55
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  github: ^9.12.0
  google_fonts: ^4.0.4
  intl: ^0.17.0
  simple_animations: ^5.0.0+3
  url_launcher: ^6.1.10

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  github_pages: ^1.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    # - .env
    - assets/
    - assets/images/
