name: portfolio_project
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  bloc: ^8.1.1
  community_material_icon: ^5.9.55
  dartz: ^0.10.1
  device_preview: ^1.1.0
  extra_alignments: ^1.0.0+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  gap: ^3.0.0
  get_it: ^7.6.0
  github: ^9.12.0
  google_fonts: ^4.0.4
  injectable: ^2.1.1
  intl: ^0.18.0
  responsive_builder: ^0.6.4
  url_launcher: ^6.1.10

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  github_pages: ^2.0.0
  injectable_generator: ^2.1.5
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
